name: onepicker
description: Access many data by using a one picker
version: 0.0.1
homepage: https://github.com/udithperera-dev/onepicker

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: 0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.onepicker
        pluginClass: OnePicker
      ios:
        pluginClass: OnePicker
